// src/features/games/GameCard.vue
<script setup lang="ts">
import { Icon } from "@iconify/vue";
import { convertFileSrc } from "@tauri-apps/api/core";

import Button from "../../components/ui/button/Button.vue";
import Card from "../../components/ui/card/Card.vue";
import { cn } from "../../lib/utils";

defineProps<{
  title: string;
  subtitle: string;
  selected: boolean;
  pathValid: boolean;
  coverPath?: string | null;
}>();

function coverSrc(path: string | null | undefined): string | null {
  if (!path) return null;
  try {
    return convertFileSrc(path);
  } catch {
    return null;
  }
}

const emit = defineEmits<{
  (e: "select"): void;
  (e: "start"): void;
  (e: "settings"): void;
}>();
</script>

<template>
  <Card
    :class="cn('flex items-center gap-3 p-3 transition', selected && 'ring-2 ring-zinc-900/10 dark:ring-zinc-50/10')">
    <button type="button" class="flex min-w-0 flex-1 items-center gap-3 text-left" @click="emit('select')">
      <div
        class="size-14 shrink-0 overflow-hidden rounded-lg bg-linear-to-br from-zinc-200 to-zinc-100 dark:from-zinc-800 dark:to-zinc-900">
        <img v-if="coverSrc(coverPath)" :src="coverSrc(coverPath)!" alt="" class="h-full w-full object-cover" />
      </div>
      <div class="min-w-0 flex-1">
        <div class="flex items-center gap-2">
          <div class="truncate text-sm font-semibold">{{ title }}</div>
          <span v-if="!pathValid"
            class="inline-flex items-center rounded-md bg-red-600 px-2 py-0.5 text-[11px] font-medium text-white">
            路径无效
          </span>
        </div>
        <div class="mt-0.5 truncate text-xs text-zinc-500 dark:text-zinc-400">{{ subtitle }}</div>
      </div>
    </button>

    <div class="ml-auto flex shrink-0 items-center gap-2">
      <Button size="sm" @click.stop="emit('start')">
        <Icon icon="ri:play-line" class="size-4" />
      </Button>
      <Button variant="secondary" size="sm" @click.stop="emit('settings')">
        <Icon icon="ri:settings-3-line" class="size-4" />
      </Button>
    </div>
  </Card>
</template>

// src/components/games/GameCard.tsx
import { useMemo } from "react";
import { Icon } from "@iconify/react";
import { convertFileSrc } from "@tauri-apps/api/core";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { getEngineDisplayName, getEngineIcon } from "@/constants/engines";
import { formatRelativeTime } from "@/lib/utils";
import type { GameDto } from "@/types";

interface GameCardProps {
  game: GameDto;
  onLaunch?: () => void;
  onEdit?: () => void;
  onDelete?: () => void;
}

export default function GameCard({ game, onLaunch, onEdit, onDelete }: GameCardProps) {
  const coverSrc = useMemo(() => {
    if (!game.coverPath) return "";
    try {
      return convertFileSrc(game.coverPath);
    } catch {
      return `asset://localhost/${game.coverPath}`;
    }
  }, [game.coverPath]);

  return (
    <div className="group relative flex items-center gap-3 rounded-xl border bg-card px-4 py-2.5 text-card-foreground transition-all hover:bg-muted/40 hover:shadow-md">
      {/* 封面图 */}
      <div className="h-12 w-12 shrink-0 overflow-hidden rounded-md bg-muted">
        {game.coverPath ? (
          <img
            src={coverSrc}
            alt={game.title}
            className="h-full w-full object-cover"
          />
        ) : (
          <div className="flex h-full w-full items-center justify-center bg-linear-to-br from-muted to-muted/50">
            <Icon
              icon={getEngineIcon(game.engineType)}
              className="h-6 w-6 text-muted-foreground/40"
            />
          </div>
        )}
      </div>

      {/* 游戏信息 */}
      <div className="flex min-w-0 flex-1 flex-col gap-1">
        <div className="flex items-center gap-2">
          <h3 className="truncate text-sm font-semibold" title={game.title}>
            {game.title}
          </h3>
          {!game.pathValid && (
            <Badge variant="destructive" className="h-4 px-2 text-[10px]">
              路径无效
            </Badge>
          )}
        </div>
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <Icon icon={getEngineIcon(game.engineType)} className="h-3.5 w-3.5" />
          <span className="truncate">{getEngineDisplayName(game.engineType)}</span>
          {game.lastPlayedAt && (
            <span className="truncate">· {formatRelativeTime(game.lastPlayedAt)}</span>
          )}
        </div>
      </div>

      {/* 操作按钮 */}
      <div className="flex shrink-0 items-center gap-2">
        <Button size="icon" className="h-7 w-7" title="启动游戏" onClick={onLaunch}>
          <Icon icon="ri:play-fill" className="h-3.5 w-3.5" />
        </Button>
        <Button
          variant="secondary"
          size="icon"
          className="h-7 w-7"
          title="编辑"
          onClick={onEdit}
        >
          <Icon icon="ri:settings-3-line" className="h-3.5 w-3.5" />
        </Button>
        <Button
          variant="ghost"
          size="icon"
          className="h-7 w-7 text-muted-foreground hover:text-destructive"
          title="删除"
          onClick={onDelete}
        >
          <Icon icon="ri:delete-bin-line" className="h-3.5 w-3.5" />
        </Button>
      </div>
    </div>
  );
}
