// src/components/settings/ManagementDialog.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from 'vue'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Separator } from '@/components/ui/separator'
import { Switch } from '@/components/ui/switch'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { getEngines, getIntegrationStatus, setIntegrationSettings } from '@/lib/api'
import { ScrollArea } from '@/components/ui/scroll-area'
import type { EngineDto } from '@/types'

interface Props {
  open: boolean
  showStatusBar: boolean
}

interface Emits {
  (e: 'update:open', value: boolean): void
  (e: 'update:showStatusBar', value: boolean): void
  (e: 'downloadNwjs'): void
  (e: 'cleanupContainers'): void
  (e: 'updateEngine', engine: EngineDto): void
  (e: 'removeEngine', engine: EngineDto): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

const engines = ref<EngineDto[]>([])
const loading = ref(false)
const bottlesLoading = ref(false)
const bottlesAvailable = ref(false)
const bottlesInstalled = ref(false)
const bottlesEnabled = ref(false)
const bottlesList = ref<string[]>([])
const defaultBottle = ref('')
const bottlesInstallCommand = 'flatpak install flathub com.usebottles.bottles'

async function fetchEngines() {
  loading.value = true
  try {
    engines.value = await getEngines()
  } catch (e) {
    console.error('获取运行器失败:', e)
  } finally {
    loading.value = false
  }
}

async function fetchBottlesStatus() {
  bottlesLoading.value = true
  try {
    const status = await getIntegrationStatus('bottles')
    const options = status.options ?? {}
    bottlesAvailable.value = status.available
    bottlesInstalled.value = options.installed ?? status.available
    bottlesEnabled.value = status.enabled
    bottlesList.value = options.bottles ?? []
    defaultBottle.value = options.defaultBottle ?? ''
  } catch (e) {
    bottlesAvailable.value = false
    bottlesInstalled.value = false
    bottlesEnabled.value = false
    bottlesList.value = []
    defaultBottle.value = ''
    console.error('获取 Bottles 状态失败:', e)
  } finally {
    bottlesLoading.value = false
  }
}

async function updateBottlesEnabled(value: boolean) {
  bottlesEnabled.value = value
  try {
    await setIntegrationSettings({ key: 'bottles', enabled: value })
  } catch (e) {
    console.error('设置 Bottles 启用状态失败:', e)
  }
}

async function updateDefaultBottle(value: string) {
  defaultBottle.value = value
  try {
    await setIntegrationSettings({
      key: 'bottles',
      options: { defaultBottle: value || '' },
    })
  } catch (e) {
    console.error('设置默认 Bottle 失败:', e)
  }
}

onMounted(() => {
  fetchEngines()
  fetchBottlesStatus()
  window.addEventListener('gm:refresh-engines', fetchEngines)
})

onUnmounted(() => {
  window.removeEventListener('gm:refresh-engines', fetchEngines)
})

watch(
  () => props.open,
  (open) => {
    if (open) {
      fetchEngines()
      fetchBottlesStatus()
    }
  }
)
</script>

<template>
  <Dialog :open="open" @update:open="(v) => emit('update:open', v)">
    <DialogContent class="sm:max-w-lg">
      <DialogHeader>
        <DialogTitle>管理</DialogTitle>
        <DialogDescription>应用运行与维护相关操作</DialogDescription>
      </DialogHeader>

      <ScrollArea class="max-h-[70vh] pr-3">
        <div class="space-y-4">
          <div class="flex items-center justify-between rounded-md border px-3 py-2">
            <div>
              <div class="text-sm font-medium">显示状态栏</div>
              <div class="text-xs text-muted-foreground">后台任务与进度信息展示</div>
            </div>
            <Switch :model-value="showStatusBar"
              @update:model-value="(v) => emit('update:showStatusBar', Boolean(v))" />
          </div>

          <Separator />

          <div class="space-y-2">
            <Button variant="secondary" class="w-full justify-start" @click="emit('downloadNwjs')">
              下载 NW.js
            </Button>
            <Button variant="secondary" class="w-full justify-start" @click="emit('cleanupContainers')">
              清理无用容器
            </Button>
          </div>

          <Separator />

          <div class="space-y-2">
            <div class="flex items-center justify-between">
              <div class="text-sm font-medium">已安装运行器</div>
              <Button variant="ghost" size="sm" :disabled="loading" @click="fetchEngines">
                刷新
              </Button>
            </div>
            <div v-if="engines.length === 0" class="text-xs text-muted-foreground">
              暂无已安装运行器
            </div>
            <div v-else class="space-y-2">
              <div v-for="engine in engines" :key="engine.id"
                class="flex items-center justify-between rounded-md border px-3 py-2 text-sm">
                <div class="min-w-0">
                  <div class="truncate font-medium">{{ engine.name }}</div>
                  <div class="text-xs text-muted-foreground">
                    {{ engine.engineType }} · {{ engine.version }}
                  </div>
                </div>
                <div class="flex items-center gap-2">
                  <Button variant="ghost" size="sm" @click="emit('updateEngine', engine)">更新</Button>
                  <Button variant="destructive" size="sm" @click="emit('removeEngine', engine)">卸载</Button>
                </div>
              </div>
            </div>
            <div class="text-xs text-muted-foreground">
              RPG Maker MV/MZ 使用 NW.js 运行时
            </div>
          </div>

          <Separator />

          <div v-if="bottlesAvailable" class="space-y-2">
            <div class="flex items-center justify-between">
              <div class="text-sm font-medium">Bottles</div>
              <Button variant="ghost" size="sm" :disabled="bottlesLoading" @click="fetchBottlesStatus">
                刷新
              </Button>
            </div>

            <div class="flex items-center justify-between rounded-md border px-3 py-2">
              <div>
                <div class="text-sm font-medium">启用 Bottles</div>
                <div class="text-xs text-muted-foreground">用于 Windows EXE（Linux）</div>
              </div>
              <Switch :model-value="bottlesEnabled" :disabled="bottlesLoading || !bottlesInstalled"
                @update:model-value="(v) => updateBottlesEnabled(Boolean(v))" />
            </div>

            <div v-if="!bottlesInstalled" class="rounded-md border px-3 py-2 text-xs text-muted-foreground">
              <div class="mb-1">该功能在你的系统上不可用。</div>
              <div>To add it, please run:</div>
              <div class="mt-2 rounded bg-muted px-2 py-1 font-mono">{{ bottlesInstallCommand }}</div>
            </div>

            <div v-else class="space-y-2">
              <div class="text-xs text-muted-foreground">选择默认 Bottle，用于 Windows EXE</div>
              <Select :model-value="defaultBottle"
                :disabled="bottlesLoading || bottlesList.length === 0 || !bottlesEnabled"
                @update:model-value="(v) => updateDefaultBottle(String(v))">
                <SelectTrigger>
                  <SelectValue placeholder="选择 Bottle" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem v-for="name in bottlesList" :key="name" :value="name">
                    {{ name }}
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </div>
      </ScrollArea>

      <DialogFooter>
        <Button variant="ghost" @click="emit('update:open', false)">关闭</Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

// src/components/settings/ManagementDialog.tsx
import { useEffect, useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Switch } from "@/components/ui/switch";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import type { EngineDto } from "@/types";

interface ManagementDialogProps {
  open: boolean;
  showStatusBar: boolean;
  onOpenChange?: (open: boolean) => void;
  onShowStatusBarChange?: (v: boolean) => void;
  onDownloadNwjs?: () => void;
  onCleanupContainers?: () => void;
  onUpdateEngine?: (engine: EngineDto) => void;
  onRemoveEngine?: (engine: EngineDto) => void;
}

export default function ManagementDialog({
  open,
  showStatusBar,
  onOpenChange,
  onShowStatusBarChange,
  onDownloadNwjs,
  onCleanupContainers,
  onUpdateEngine,
  onRemoveEngine,
}: ManagementDialogProps) {
  const [engines, setEngines] = useState<EngineDto[]>([]);
  const [loading, setLoading] = useState(false);
  const [bottlesLoading, setBottlesLoading] = useState(false);
  const [bottlesAvailable, setBottlesAvailable] = useState(false);
  const [bottlesInstalled, setBottlesInstalled] = useState(false);
  const [bottlesEnabled, setBottlesEnabled] = useState(false);
  const [bottlesList, setBottlesList] = useState<string[]>([]);
  const [defaultBottle, setDefaultBottle] = useState("");
  const bottlesInstallCommand = 'flatpak install flathub com.usebottles.bottles';

  async function fetchEngines() {
    setLoading(true);
    try {
      const list = await import("@/lib/api").then((m) => m.getEngines());
      setEngines(list);
    } catch (e) {
      console.error("获取运行器失败:", e);
    } finally {
      setLoading(false);
    }
  }

  async function fetchBottlesStatus() {
    setBottlesLoading(true);
    try {
      const status = await import("@/lib/api").then((m) => m.getIntegrationStatus("bottles"));
      const options = status.options ?? {};
      setBottlesAvailable(status.available);
      setBottlesInstalled(options.installed ?? status.available);
      setBottlesEnabled(status.enabled);
      setBottlesList(options.bottles ?? []);
      setDefaultBottle(options.defaultBottle ?? "");
    } catch (e) {
      setBottlesAvailable(false);
      setBottlesInstalled(false);
      setBottlesEnabled(false);
      setBottlesList([]);
      setDefaultBottle("");
      console.error("获取 Bottles 状态失败:", e);
    } finally {
      setBottlesLoading(false);
    }
  }

  async function updateBottlesEnabled(value: boolean) {
    setBottlesEnabled(value);
    try {
      await import("@/lib/api").then((m) =>
        m.setIntegrationSettings({ key: "bottles", enabled: value }),
      );
    } catch (e) {
      console.error("设置 Bottles 启用状态失败:", e);
    }
  }

  async function updateDefaultBottle(value: string) {
    setDefaultBottle(value);
    try {
      await import("@/lib/api").then((m) =>
        m.setIntegrationSettings({ key: "bottles", options: { defaultBottle: value || "" } }),
      );
    } catch (e) {
      console.error("设置默认 Bottle 失败:", e);
    }
  }

  useEffect(() => {
    if (open) {
      fetchEngines();
      fetchBottlesStatus();
      const handler = () => fetchEngines();
      window.addEventListener("gm:refresh-engines", handler);
      return () => window.removeEventListener("gm:refresh-engines", handler);
    }
  }, [open]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>管理</DialogTitle>
          <DialogDescription>应用运行与维护相关操作</DialogDescription>
        </DialogHeader>
        <ScrollArea className="max-h-[70vh] pr-3">
          <div className="space-y-4">
            <div className="flex items-center justify-between rounded-md border px-3 py-2">
              <div>
                <div className="text-sm font-medium">显示状态栏</div>
                <div className="text-xs text-muted-foreground">后台任务与进度信息展示</div>
              </div>
              <Switch
                checked={showStatusBar}
                onCheckedChange={(v) => onShowStatusBarChange?.(Boolean(v))}
              />
            </div>

            <Separator />

            <div className="space-y-2">
              <Button variant="secondary" className="w-full justify-start" onClick={onDownloadNwjs}>
                下载 NW.js
              </Button>
              <Button variant="secondary" className="w-full justify-start" onClick={onCleanupContainers}>
                清理无用容器
              </Button>
            </div>

            <Separator />

            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <div className="text-sm font-medium">已安装运行器</div>
                <Button variant="ghost" size="sm" disabled={loading} onClick={fetchEngines}>
                  刷新
                </Button>
              </div>
              {engines.length === 0 ? (
                <div className="text-xs text-muted-foreground">
                  暂无已安装运行器
                </div>
              ) : (
                engines.map((engine) => (
                  <div
                    key={engine.id}
                    className="flex items-center justify-between rounded-md border px-3 py-2 text-sm"
                  >
                    <div className="min-w-0">
                      <div className="truncate font-medium">{engine.name}</div>
                      <div className="text-xs text-muted-foreground">
                        {engine.engineType} · {engine.version}
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <Button variant="ghost" size="sm" onClick={() => onUpdateEngine?.(engine)}>
                        更新
                      </Button>
                      <Button variant="destructive" size="sm" onClick={() => onRemoveEngine?.(engine)}>
                        卸载
                      </Button>
                    </div>
                  </div>
                ))
              )}
              <div className="text-xs text-muted-foreground">
                RPG Maker MV/MZ 使用 NW.js 运行时
              </div>
            </div>

            <Separator />

            {bottlesAvailable && (
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <div className="text-sm font-medium">Bottles</div>
                  <Button variant="ghost" size="sm" disabled={bottlesLoading} onClick={fetchBottlesStatus}>
                    刷新
                  </Button>
                </div>

                <div className="flex items-center justify-between rounded-md border px-3 py-2">
                  <div>
                    <div className="text-sm font-medium">启用 Bottles</div>
                    <div className="text-xs text-muted-foreground">用于 Windows EXE（Linux）</div>
                  </div>
                  <Switch
                    checked={bottlesEnabled}
                    disabled={bottlesLoading || !bottlesInstalled}
                    onCheckedChange={(v) => updateBottlesEnabled(Boolean(v))}
                  />
                </div>

                {!bottlesInstalled && (
                  <div className="rounded-md border px-3 py-2 text-xs text-muted-foreground">
                    <div className="mb-1">该功能在你的系统上不可用。</div>
                    <div>To add it, please run:</div>
                    <div className="mt-2 rounded bg-muted px-2 py-1 font-mono">
                      {bottlesInstallCommand}
                    </div>
                  </div>
                )}

                {bottlesInstalled && (
                  <div className="space-y-2">
                    <div className="text-xs text-muted-foreground">
                      选择默认 Bottle，用于 Windows EXE
                    </div>
                    <Select
                      value={defaultBottle}
                      onValueChange={updateDefaultBottle}
                      disabled={bottlesLoading || bottlesList.length === 0 || !bottlesEnabled}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="选择 Bottle" />
                      </SelectTrigger>
                      <SelectContent>
                        {bottlesList.map((name) => (
                          <SelectItem key={name} value={name}>
                            {name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                )}
              </div>
            )}
          </div>
        </ScrollArea>
        <DialogFooter>
          <Button variant="ghost" onClick={() => onOpenChange?.(false)}>
            关闭
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
